### ISSUE TITLE
Example returning empty dict on selections

### ISSUE THREAD

**Issue by joelostblom** [domoritz/streamlit-vega-lite#10]
Very excited about this! Being able to emit signals from Vegalite/Altair for general processing in Python is great so thank you for working on it! I noticed it is at proof of concept stage, so just a heads up that the example is not working for me with these package versions:

```
altair              4.1.0
streamlit           0.74.1
streamlit_vega_lite 9a19fa8
```

Any selection made is returning an empty dictionary.

**Comment by domoritz** [comment]
Thanks for the heads up. I made this as a POC so Streamlit can implement this functionality natively (https://github.com/streamlit/streamlit/issues/2263, please upvote).

I just tried the example in https://github.com/domoritz/streamlit-vega-lite/blob/d2944f07604b9dc79d53c63d10f0d79e4a9290e9/streamlit_vega_lite/__init__.py#L110 as described in the readme and it works fine (with Streamlit 0.74.1). Do you see the issue here as well?

**Comment by joelostblom** [comment]
Upvoted! Thanks for pointing me to the built in example. I followed the `Dev Setup` section and after launching the `yarn` server it works perfectly! This is SO cool!!

**Comment by domoritz** [comment]
Oh, I know what's happening. If you use master, you get `_RELEASE = false` and it needs the dev server running. Why don't you install the component with pip (as I do in https://github.com/domoritz/streamlit-vega-lite-demo)?
