### ISSUE TITLE
Get user selection ID without regenerating Altair chart

### ISSUE THREAD

**Issue by chuanenlin** [domoritz/streamlit-vega-lite#20]
For `altair_component`, is it possible to disentangle getting the user selected data point (`_vgsid_`) from the rendering of the chart? For example, in the [penguin data explorer demo](https://share.streamlit.io/domoritz/streamlit-vega-lite-demo/main/demo.py), the chart regenerates when hovering over different data points.

**Comment by davidlevybooth** [comment]
I have a very similar question. I have a mouseoover that doesn't need to return an event, and a click that does. Is there a way to filter what gets returned as an event? Otherwise streamlit refreshes the entire page every time an event is returned. Thanks! `streamlit-vega-lite` is essential for creating interactive dashboards with altair + streamlit

**Comment by domoritz** [comment]
The refresh seems to be a bug in Streamlit or how we use it. @tvst may be looking at it.

**Comment by domoritz** [comment]
See https://github.com/streamlit/streamlit/issues/5024

**Comment by chuanenlin** [comment]
Might be an issue with an older Streamlit version. Upgrading to Streamlit 1.11 solves the issue for me.
